export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const RESET_QUANTITY = "RESET_QUANTITY";
export const SET_FIRSTNAME = "SET_FIRSTNAME";
export const SET_LASTNAME = "SET_LASTNAME";
export const SET_EMAIL = "SET_EMAIL";
